SELECT 
    AHO_CODIGO_COO,
    SUM(CASE WHEN aho_tipo_cta = 1 THEN TRA_MTO_DEPOSITO + TRA_MTO_INTERES - TRA_MTO_RETIRO - TRA_MTO_ISR ELSE 0 END) AS SALDO_TIPO,
    SUM(CASE WHEN aho_tipo_cta = 3 THEN TRA_MTO_DEPOSITO + TRA_MTO_INTERES - TRA_MTO_RETIRO - TRA_MTO_ISR ELSE 0 END) AS SALDO_TIPO_3
FROM 
    DBA.AHORROS 
    INNER JOIN DBA.TRANS_AHORRO ON TRA_CODIGO_CTA = AHO_CODIGO_CTA
WHERE 
    tra_fecha_trans BETWEEN '2023-01-01' AND '2024-12-30'
    AND aho_tipo_cta IN (1, 3)
    --AND AHO_CODIGO_COO = 30000007
GROUP BY 
    AHO_CODIGO_COO;


SELECT 
CRE_CODIGO_COOP,
SUM(CASE WHEN cre_fondo = 18 THEN TRC_MTO_OTORGADO-TRC_MTO_CAPITAL ELSE 0 END) AS SALDO_TIPO
FROM DBA.TRANS_CREDITO, DBA.CREDITOS 
WHERE CRE_CODIGO_CTA = TRC_CODIGO_CTA 
and trc_fecha_trans BETWEEN '01/01/2022' and '30/10/2022' 
and cre_fondo in (18,2)
--AND cre_codigo_coop =130011205  
GROUP BY CRE_CODIGO_COOP

select string('hos',1),string('hos',2)
select * EXCEPT(coop_nombre)  from dba.COOPERATIVISTAS 