SELECT * FROM "DBA"."TRANS_SEGURO"
select * from dba.TRANS_CREDITO 
select * from dba.TRANS_AHORRO where  tra_fecha_trans between '01/01/2023' and '30/12/2023' --AND AHO_CODIGO_COO = 30000007
SELECT * FROM DBA.SEGUROS
select * from dba.AHORROS

SELECT SEG_CODIGO_COOP, sum(TRS_CARGOS-TRS_PAGOS) FROM "DBA"."TRANS_SEGURO", DBA.SEGUROS 
WHERE SEG_CODIGO_CTA = TRS_CODIGO_CTA AND SEG_CODIGO_COOP =130011205 and TRS_FECHA_TRANS BETWEEN '01/06/2022' and '30/12/2023' GROUP BY  SEG_CODIGO_COOP

SELECT  DPF_CODIGO_COOP, sum(TRD_MTO_DEPOSITO-TRD_MTO_RETIROS) AS SALDODPF FROM DBA.TRANSAC_DEPOSIT, DBA.Depositos 
WHERE TRD_CODIGO_CTA = DPF_CODIGO_CTA
and trd_fecha_tran BETWEEN '01/06/2022' and '30/12/2023' and DPF_CODIGO_COOP =50000459
GROUP BY DPF_CODIGO_COOP

SELECT SUM(TRC_MTO_OTORGADO-TRC_MTO_CAPITAL) AS SUMA FROM DBA.TRANS_CREDITO, DBA.CREDITOS 
WHERE CRE_CODIGO_CTA = TRC_CODIGO_CTA 
and trc_fecha_trans BETWEEN '01/01/2022' and '30/10/2022' AND cre_codigo_coop =130011205  
GROUP BY CRE_CODIGO_COOP

SELECT AHO_CODIGO_COO,SUM(TRA_MTO_DEPOSITO+TRA_MTO_INTERES-TRA_MTO_RETIRO-TRA_MTO_ISR) AS SALDO FROM DBA.AHORROS, DBA.TRANS_AHORRO WHERE TRA_CODIGO_CTA = AHO_CODIGO_CTA
and tra_fecha_trans between '01/01/2023' and '30/12/2024' and aho_tipo_cta in (1,3)
--AND AHO_CODIGO_COO = 30000007
GROUP BY AHO_CODIGO_COO

